name: Java CI build and test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 8 ]
        arch: [ x64 ]
        dist: [ zulu ]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}, ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.arch }}
          distribution: ${{ matrix.dist }}

      - name: Compile FastDoubleParser
        run: javac -d out -encoding utf8 --module-source-path FastDoubleParser/src/main/java --module ch.randelshofer.fastdoubleparser
      - name: Compile FastDoubleParserDemo
        run: javac -d out -encoding utf8 -p out --module-source-path FastDoubleParserDemo/src/main/java --module ch.randelshofer.fastdoubleparserdemo
      - name: Run Test 1
        run: java --module-path out --module ch.randelshofer.fastdoubleparserdemo/ch.randelshofer.fastdoubleparserdemo.Main --print-confidence
      - name: Run Test 2
        run: java --module-path out --module ch.randelshofer.fastdoubleparserdemo/ch.randelshofer.fastdoubleparserdemo.Main --print-confidence FastDoubleParserDemo/data/canada.txt
...
