name: Java CI build and test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
        java: [ 8 ]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Compile FastDoubleParser
        run: javac -d out/test/FastDoubleParser -encoding utf8 -sourcepath src/main/java:test/main/java test/main/java/ch/randelshofer/fastdoubleparser/FastDoubleParserBenchmark.java
      - name: Run Test 1
        run: java --class-path out/test/FastDoubleParser ch.randelshofer.fastdoubleparser.FastDoubleParserBenchmark
      - name: Run Test 2
        run: java --class-path out/test/FastDoubleParser ch.randelshofer.fastdoubleparser.FastDoubleParserBenchmark data/canada.txt
...
